# Generalización realizada con IA
equivalencias = {
    "tomate_redondo": "tomate",
    "tomate_entero_en_conserva": "tomate",
    "mozzarella": "queso_mozzarella",
    "pechuga_de_pollo": "pollo_entero",
    "pasta_para_lasana": "pasta_lasagna",
    "queso_parmesano": "queso_sardo",
    "chocolate": "chocolate_en_polvo",
    "vainilla": "esencia_vainilla",
    "crutones": "pan_deshidratado",
    "aderezo_cesar": "aderezo",
    "queso_feta": "queso_sardo",
    "atun": "atun_en_lata",
    "queso_cheddar": "queso_sardo",
    "papas": "papa",
    "lentejas": "lenteja",
    "calabaza": "zapallo",
    "tocino": "panceta",
    "mezcla_para_panqueques": "harina_preparada",
    "quinoa": "quinoa_cruda",
    "garbanzos": "garbanzo",
    "agua_con_gas": "agua_sin_gas",
    "jarabe_de_cola": "gaseosa_base_cola",
    "vino_tinto": "vino",
    "vino_blanco": "vino",
    "cerveza_lager": "cerveza",
    "cerveza_ipa": "cerveza",
    "granos_de_cafe": "cafe_molido",
    "te_negro": "te",
    "te_verde": "te",
    "ron_blanco": "ron",
    "agua_tonica": "agua_sin_gas"
    }